"use client";

import React, { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

const faqData = [
  {
    question: "What is the main difference between Analyze and Semrush AI Toolkit?",
    answer: "Semrush AI Toolkit is primarily a visibility and sentiment tracking suite—great for understanding how your brand or content appears within AI-generated answers. Analyze, however, connects that visibility to actual traffic and conversions. It measures the tangible outcomes of AI exposure and translates them into growth actions. Semrush's toolkit is more research-oriented, while Analyze functions as an ongoing performance engine."
  },
  {
    question: "Does Analyze track real traffic from AI engines like ChatGPT, Perplexity, or Google AI Overviews?",
    answer: "Yes. Analyze pulls authenticated GA4 session data and labels which AI engine each session came from. Semrush's AI Toolkit currently tracks where your brand appears in AI answers but doesn't quantify real GA4 traffic from those appearances."
  },
  {
    question: "Can Analyze show which pages are getting AI-generated traffic?",
    answer: "Yes. Analyze lists every page receiving AI-engine visits and correlates it with the AI responses that drive those sessions. Semrush AI Toolkit focuses on brand or content mentions in AI tools, not which site pages receive the resulting traffic."
  },
  {
    question: "Does Analyze measure conversions from AI traffic?",
    answer: "Yes. Analyze connects visibility to outcomes, tracking sign-ups, purchases, or leads generated by AI-engine visitors. Semrush's toolkit does not include conversion tracking; it emphasizes exposure metrics and trend scores."
  },
  {
    question: "How does Analyze identify opportunities or actions to improve AI visibility?",
    answer: "Analyze produces prioritized, data-driven recommendations—such as optimizing underperforming pages in engines showing declining trend lines or targeting queries where competitors are gaining traction. Semrush AI Toolkit surfaces keyword and prompt opportunities but leaves conversion and prioritization logic to you."
  },
  {
    question: "Can Analyze monitor competitors' AI visibility too?",
    answer: "Yes. Analyze provides side-by-side comparisons of your and your competitors' AI visibility, traffic, and conversion trends. Semrush AI Toolkit also offers competitor tracking but largely focuses on visibility and sentiment rather than traffic or ROI."
  },
  {
    question: "How easy is it to set up Analyze compared to Semrush AI Toolkit?",
    answer: "Analyze requires a quick GA4 connection and domain setup. Semrush's toolkit is part of a larger platform that needs project configuration, keyword imports, and app-center integrations, which can take longer."
  },
  {
    question: "How much does Analyze cost?",
    answer: "Analyze costs $99 per month flat. Semrush AI Toolkit is an add-on within Semrush, typically requiring a paid base plan plus the AI-visibility module, leading to a higher combined monthly spend."
  },
  {
    question: "Who is Analyze best suited for?",
    answer: "Analyze is built for SMBs, agencies, and marketing teams seeking direct AI-traffic attribution, conversion tracking, and clear action guidance. Semrush AI Toolkit is ideal for SEO professionals needing broader visibility analytics across AI but not necessarily tied to GA4 outcomes."
  },
  {
    question: "Can I use Analyze alongside Semrush AI Toolkit or other analytics tools?",
    answer: "Yes. Many teams use both: Semrush for market-wide visibility benchmarking and Analyze for actual performance and ROI measurement. They complement one another—Semrush helps you see where you appear, while Analyze shows what that appearance is worth in traffic and conversions."
  }
];

export const FaqSemrushAiToolkit = () => {
  const [openItems, setOpenItems] = useState<number[]>([]);

  const toggleItem = (index: number) => {
    setOpenItems(prev => 
      prev.includes(index) 
        ? prev.filter(i => i !== index)
        : [...prev, index]
    );
  };

  return (
    <section className="py-16 lg:py-20 bg-gray-100">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl tracking-tight md:text-4xl lg:text-5xl text-gray-900 mb-4">
              Analyze vs Semrush AI Toolkit: FAQ
            </h2>
            <p className="text-lg text-gray-600">
              Common questions about choosing between Analyze and Semrush AI Toolkit for AI visibility tracking
            </p>
          </div>

          <div className="space-y-4">
            {faqData.map((item, index) => (
              <div key={index} className="bg-gray-50 rounded-lg border border-gray-200">
                <button
                  onClick={() => toggleItem(index)}
                  className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-gray-100 transition-colors"
                >
                  <h3 className="text-lg font-semibold text-gray-900 pr-4">
                    {item.question}
                  </h3>
                  {openItems.includes(index) ? (
                    <ChevronUp className="w-5 h-5 text-gray-500 flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-500 flex-shrink-0" />
                  )}
                </button>
                {openItems.includes(index) && (
                  <div className="px-6 pb-4">
                    <p className="text-gray-700 leading-relaxed">
                      {item.answer}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
